#!/usr/bin/with-contenv bash

echo "[init-cron] Export environment for use in crontab"
declare -p | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID' > /container.env

CRONTAB="$CRON_TIMESPEC python3 /plugin.video.mediathekview/mvupdate3 mysql -vv -d $MYSQL_DATABASE -u $MYSQL_USER -p $MYSQL_PASSWORD -f"
echo "[init-cron] Install crontab:  $CRONTAB"
echo "SHELL=/bin/bash
BASH_ENV=/container.env
$CRONTAB > /tmp/stdout 2> /tmp/stderr
# This extra line makes it a valid cron
" | crontab -

echo "[init-cron] Create custom stdout and stderr named pipes"
if [ ! -p /tmp/stdout ]; then 
	mkfifo /tmp/stdout
	chmod 0666 /tmp/stdout
fi

if [ ! -p /tmp/stderr ]; then 
        mkfifo /tmp/stderr
        chmod 0666 /tmp/stderr
fi

# Have the main Docker process tail the files to produce stdout and stderr 
# for the main process that Docker will actually show in docker logs.
tail -f -n 100 /tmp/stdout &
tail -f -n 100 /tmp/stderr >&2 &

echo "[init-cron] Start cron"
/usr/sbin/cron -f -L 1 &
